[package]
name = "tiny"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
repository = "https://github.com/osa1/tiny"
readme = "README.md"
license = "MIT"
keywords = ["irc"]
categories = ["network-programming"]
description = "An IRC client"

[workspace]

[lib]
name = "tiny"
path = "src/lib.rs"

[[bin]]
name = "tiny"
path = "bin/main.rs"

[dependencies]
libc = "0.2.22"
mio = "0.6.9"
net2 = "0.2.23"
notify-rust = "3.4.0"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_yaml = "0.7.1"
term_input = { path = "term_input/" }
termbox_simple = { path = "termbox/" }
time = "0.1"

[profile.release]
lto = true
